spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zzzsheep
    username: zzzsheep
    password: ?!Pan2005929
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

plaid:
  client-id: your_plaid_client_id
  secret: your_plaid_secret
  environment: sandbox

server:
  port: 8080

application:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000  # a day in milliseconds
    token-prefix: "Bearer "